/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  uint32_t volatile *pClockControlReg = (uint32_t*) 0x40021034;  //RCC_IOPENR (0x34 RCC_Offset) 0x40021034
  uint32_t volatile *pPortDModeReg    = (uint32_t*) 0x50000000;  //GPIOA baseAdrr               0x50000000
  uint32_t volatile *pPortDOutReg     = (uint32_t*) 0x50000014;  //GPIOA baseAdrr + 0x14        0x50000C14

  //Using PC10
  uint32_t volatile *pPortCModeReg    = (uint32_t*) 0x50000800;  //GPIOC baseAdrr               0x50000800
  uint32_t volatile *pPortCInReg      = (uint32_t*) 0x50000810;  //GPIOA baseAdrr + 0x10        0x50000810

  //1. Enable the clock for GPOID peripheral in the AHB1ENR
  *pClockControlReg |= ((1<<2)|(1 << 0));  //EN GPIOA in RCC_IOPENR by Setting bit0 -> 1, GPIOC bit2 -> 1

  //2. Configure the mode of the IO pin as an output
  *pPortDModeReg &= ~(3 << 10);  //Clear 10th and 11th bit positions
  *pPortDModeReg |=  (1 << 10);  //Set the 10th bit position to 1, 11th to 0 : 0x00000400

  *pPortCModeReg &= ~(3<<20);   //Set bit 20 and 21 to 00 - Input Mode

  uint8_t pinStatus = 0;

  while(1)
  {
    pinStatus = (uint8_t) ((*pPortCInReg >> 10) & (0x01));

    if(pinStatus)
    {
      //3. Set 5th bit of the output data register HIGH to turn LED4 ON
      *pPortDOutReg |= (1 << 5);

    }
    else
    {
      //Turn Off LED4
      *pPortDOutReg &= ~(1 << 5);
    }

  }

 //while(1);

}

